version: '3.7'

services:
  database_ignite_monolito:
    image: postgres
    container_name: database_ignite_monolito
    restart: always
    ports:
      - 6667:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    ports:
      - 6666:6379

  app_monolito:
    build: .
    container_name: rentx_monolito
    ports:
      - 6668:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite_monolito
    depends_on:
      - database_ignite_monolito

volumes:
  pgdata:
    driver: local
